### ISSUE TITLE
Scan Redesigned Sites and Create Sample GitHub Tickets

### ISSUE THREAD

**Issue by bbertucc** [EqualifyEverything/eudaimonia-wp#1]
WordPress has been under a redesign since our last scan.

We will need to prioritize the scanning of redesigned sites.

I asked for a list of redesigned sites, [here](https://wordpress.slack.com/archives/C04U953K77A/p1716839182883559). Any answers to that question should be logged in [websites.csv](https://github.com/EqualifyEverything/eudaimonia-wp/blob/main/websites.csv), adding `TRUE` to the "Prioritize?" column for redesigned sites or single pages that need to be scanned.

@jwgoedert will initiate the scan and upload a new SQL download of the Equalify output.

The outcome should be an updated db file, replacing this: https://github.com/EqualifyEverything/eudaimonia-wp/blob/main/equalify_db.sql.gz

Once that is done, @jwgoedert will start generating sample GitHub tickets that we can share in the [Making WordPress accessibility-testing Slack](https://wordpress.slack.com/archives/CEKKABGJD).

**Comment by bbertucc** [comment]
@jwgoedert - Before our Wednesday meeting, would you mind making sure you have the latest version of the [Equalify v1-rc5 brach](https://github.com/EqualifyEverything/equalify/tree/v1-rc5) running locally? I will send you .env variables.

**Comment by jwgoedert** [comment]
@bbertucc Can do, will pull down latest tomorrow and let you know if I have any issues
